### ISSUE TITLE
Logout possible?

### ISSUE THREAD

**Issue by bainewedlock** [mogest/simple_google_auth#6]
This is super simple to use!

I was wondering if logout is possible. (I wanted to test if only certain emails can login, but I can't seem to logout again)

**Comment by mogest** [comment]
Hi @bainewedlock, depends what you mean by logout.  It doesn't have functionality to invalidate the Google access token, but you can log the user out of your site by doing this in a controller:

```
session.delete(SimpleGoogleAuth.config.state_session_key_name)
```

or if there's nothing in your session that you want to keep, even more simply:

```
session.clear
```

**Comment by bainewedlock** [comment]
perfect, thanks!
